server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexanderIab/crm-system-ms-properties
          basedir: file://C:/crm-system-ms-properties
          clone-on-start: true
          username: AlexanderIab
          password: {cipher}MuBXoaEidR1/ixPvDwCS04TmN5rOSzsJ8cuttFDU8q5n+U/UvBwfr0Bf4nOjvz2T
          default-label: main